import './globals.css'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Background from './components/Background'
import { background } from './assets'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Project Auros',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }){
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='bg'>
          <Background />
          <div className=' absolute top-0 left-0 '>
            <Navbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}